package main

import (
	"fmt"
	"math/rand"
	"os"
	"sync"
	"time"

	"github.com/spf13/pflag"

	"zeptile.com/go_clicker/internal/color"
	"zeptile.com/go_clicker/internal/input"
	"zeptile.com/go_clicker/internal/platform"
)

type Configuration struct {
	debugMode           bool
	randomMode          bool
	colorMode           bool
	intervalMs          int64
	randomIntervalStart int64
	randomIntervalEnd   int64
	colorTolerance      int
	colorsFile          string
}

var running = false
var version = "dev"
var config Configuration
var targetColors []color.TargetColor
var colorMu sync.RWMutex

func main() {
	config = parseConsoleArguments()

	if config.colorsFile != "" {
		config.colorMode = true
		loaded, err := color.LoadFile(config.colorsFile, config.colorTolerance)
		if err != nil {
			fmt.Printf("Error loading colors file: %v\n", err)
			os.Exit(1)
		}
		colorMu.Lock()
		targetColors = append(targetColors, loaded...)
		colorMu.Unlock()
	}

	toggleCh, sampleCh := input.Setup()

	wg := sync.WaitGroup{}
	wg.Add(3)

	// Click loop
	go func() {
		defer wg.Done()

		for {
			if !running {
				time.Sleep(10 * time.Millisecond)
				continue
			}

			rand.Seed(time.Now().UnixNano())
			var waitForMs int

			if config.randomMode {
				waitForMs = int(config.randomIntervalStart) + rand.Intn(int(config.randomIntervalEnd-config.randomIntervalStart))
			} else {
				waitForMs = int(config.intervalMs)
			}

			time.Sleep(time.Duration(waitForMs) * time.Millisecond)

			if config.colorMode {
				matched, debugInfo := isColorMatch()
				if !matched {
					if config.debugMode {
						fmt.Println("[Debug] Color mismatch, skipping click.", debugInfo)
					}
					continue
				}
			}

			platform.Click()
			if config.debugMode {
				fmt.Printf("[Debug] Clicked after waiting %dms\n", waitForMs)
			}
		}
	}()

	// Toggle
	go func() {
		defer wg.Done()

		for range toggleCh {
			if !running {
				fmt.Println("Resumed")
			} else {
				fmt.Println("Paused")
			}
			running = !running
		}
	}()

	// Sample color
	go func() {
		defer wg.Done()

		for range sampleCh {
			x, y := platform.CursorPos()
			r, g, b, err := platform.GetPixelColor(x, y)
			if err != nil {
				fmt.Printf("Error sampling color: %v\n", err)
				continue
			}

			tol := config.colorTolerance
			tc := color.TargetColor{R: r, G: g, B: b, Tolerance: tol, Sampled: true}

			colorMu.Lock()
			targetColors = append(targetColors, tc)
			colorMu.Unlock()

			fmt.Printf("Sampled color at (%d, %d): R:%d G:%d B:%d tol:%d [%d colors loaded]\n",
				x, y, r, g, b, tol, len(targetColors))
		}
	}()

	input.PrintControlInfo()

	if config.colorMode {
		fmt.Println("Color mode enabled (default tolerance:", config.colorTolerance, ")")
		if config.colorsFile != "" {
			fmt.Printf("Loaded %d colors from %s\n", len(targetColors), config.colorsFile)
			if config.debugMode {
				for i, c := range targetColors {
					fmt.Printf("  %d. \033[48;2;%d;%d;%dm    \033[0m #%02x%02x%02x (R:%d G:%d B:%d) tol:%d\n",
						i+1, c.R, c.G, c.B, c.R, c.G, c.B, c.R, c.G, c.B, c.Tolerance)
				}
			}
		}
	}

	wg.Wait()
}

func isColorMatch() (bool, string) {
	colorMu.RLock()
	tc := targetColors
	colorMu.RUnlock()

	if len(tc) == 0 {
		return false, "no colors loaded"
	}

	x, y := platform.CursorPos()
	r, g, b, err := platform.GetPixelColor(x, y)
	if err != nil {
		return false, fmt.Sprintf("pixel error: %v", err)
	}

	return color.MatchesAnyColor(r, g, b, tc)
}

func parseConsoleArguments() Configuration {
	var config Configuration
	var showVersion bool

	pflag.BoolVar(&config.randomMode, "random", false, "Flag to enable random mode, click interval is random between 0 and randomIntervalEnd")
	pflag.BoolVar(&config.debugMode, "debug", false, "Flag to enable debug mode, prints debug logs to console")
	pflag.BoolVar(&config.colorMode, "color", false, "Flag to enable color mode, only clicks when pixel under cursor matches target color")

	pflag.Int64Var(&config.intervalMs, "intervalMs", 50, "Interval in milliseconds to click in normal mode")
	pflag.Int64Var(&config.randomIntervalStart, "randomIntervalStart", 0, "Minimum interval in milliseconds for random mode")
	pflag.Int64Var(&config.randomIntervalEnd, "randomIntervalEnd", 100, "Maximum interval in milliseconds for random mode")
	pflag.IntVar(&config.colorTolerance, "colorTolerance", 30, "RGB tolerance per channel for color matching (0-255)")
	pflag.StringVar(&config.colorsFile, "colorsFile", "", "Path to colors.json file generated by colorpicker tool")
	pflag.BoolVar(&showVersion, "version", false, "Print version and exit")

	pflag.Parse()

	if showVersion {
		fmt.Println(version)
		os.Exit(0)
	}

	if config.randomMode {
		if config.randomIntervalStart < 0 {
			fmt.Println("Random interval start must be >= 0")
			pflag.PrintDefaults()
			panic("Random interval start must be >= 0")
		}
		if config.randomIntervalEnd <= config.randomIntervalStart {
			fmt.Println("Random interval end must be greater than start")
			pflag.PrintDefaults()
			panic("Random interval end must be greater than start")
		}
	} else {
		if config.intervalMs < 0 {
			fmt.Println("Interval must be greater than 0")
			pflag.PrintDefaults()
			panic("Interval must be greater than 0")
		}
	}

	return config
}
